version: "3.9"

services:
  web:
    build:
      context: dockerfiles
      dockerfile: web/Dockerfile
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - ../Cloudlog/:/var/www/html/
    ports:
      - '80:80'
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - internal
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db: